<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net45;net6.0</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Authors>rockey627</Authors>
		<PackageTags>C# sql mysql sqlserver Expression Eval Evaluator Execute Function Compile Compiler Script Scripting 脚本执行 动态脚本 表达式 计算</PackageTags>
		<PackageLicenseUrl>https://gitee.com/rockey627/ascript/blob/master/LICENSE</PackageLicenseUrl>
		<PackageProjectUrl>https://gitee.com/rockey627/ascript</PackageProjectUrl>
		<Description>
			<![CDATA[
基于AScript扩展的SQL脚本语言；
快速开始：
// 添加sql脚本语言
Script.Langs.Set("sql", SqlLang.Instance);
string s = @"
@lang sql
select name,age from list where name like 'to%' and age=10
";
var script = new Script();
script.Context.SetVar("list", new [] { new Person("tommy", 15), new Person("tony", 10) });
var list = script.Eval<IEnumerable<dynamic>>(s).ToList();
Assert.AreEqual(1, list.Count);
Assert.AreEqual("tony", list[0].name);
Assert.AreEqual(10, list[0].age);
			]]>
		</Description>
		<Version>0.0.4.0</Version>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>AScript1.0.5</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AScript\AScript.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
