<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net45;net6.0;net8.0</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Authors>rockey627</Authors>
		<PackageTags>C# JavaScript js fs file stream</PackageTags>
		<PackageLicenseUrl>https://gitee.com/rockey627/ascript/blob/master/LICENSE</PackageLicenseUrl>
		<PackageProjectUrl>https://gitee.com/rockey627/ascript</PackageProjectUrl>
		<Description>
			<![CDATA[
js fs模块；
快速开始：
// 注册js脚本语言
Script.Langs.Set("js", JavaScriptLang.Instance);
// 语言环境中注册fs模块
JavaScriptLang.Instance.AddModule("fs", new JavaScriptFileSystemModule());
// 引入fs并调用相关方法
string s = @"
var fs = require('fs');
fs.writeFileSync('test.txt', 'hello world', 'utf-8');
fs.readFileSync('test.txt', 'utf-8');
";
var script = new Script();
script.Context.Langs = new [] { "js" };
// 或者在当前上下文环境中注册fs模块
//script.Context.AddModule("fs", new JavaScriptFileSystemModule());
var result = script.Eval(s);
Assert.AreEqual("hello world", result);
			]]>
		</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>0.1.0.0</Version>
		<PackageReleaseNotes>AScript1.6.0；添加net6.0/net8.0框架</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AScript\AScript.csproj" />
	</ItemGroup>

</Project>
