<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netstandard2.0;netstandard2.1;net45</TargetFrameworks>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <Authors>rockey627</Authors>
	  <PackageTags>AScript Newtonsoft json</PackageTags>
	  <PackageLicenseUrl>https://gitee.com/rockey627/ascript/blob/master/LICENSE</PackageLicenseUrl>
	  <PackageProjectUrl>https://gitee.com/rockey627/ascript</PackageProjectUrl>
	  <Description>
		  <![CDATA[
对Newtonsoft.Json包中的json对象进行扩展；
快速开始：
// 方式1：在顶级上下文中添加json扩展
ScriptContext.Root.AddExtension(new NewtonsoftJsonExtensionObject());
// 方式2：在指定语言中添加json扩展
CSharpLang.Instance.AddExtension(new NewtonsoftJsonExtensionObject());
// 使用
string s = @"
var data = '{a:1,b:2}'.ToJson();
data.a + data.b
";
var script = new Script();
var result = script.Eval(s);
Assert.AreEqual(3, result);
			]]>
	  </Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <Version>1.0.0.0</Version>
	  <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\AScript\AScript.csproj" />
  </ItemGroup>
</Project>
